In [1]:
import numpy as np

sensor_data = np.array([
    [12, 15, 14, 10, 13],
    [20, 22, 19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])

avg_per_machine = np.mean(sensor_data, axis=1)
print("Average per machine:", avg_per_machine)
max_per_column = np.max(sensor_data, axis=0)
print("Max per column:", max_per_column)

normalized_data = sensor_data / max_per_column
print("Normalized data:\n", normalized_data)

machines_above_20 = np.where(avg_per_machine > 20)[0]
print("Machines with avg > 20:", machines_above_20)

reshaped_data = sensor_data.reshape(2, 10)
print("Reshaped data:\n", reshaped_data)

Average per machine: [12.8 20.  29.  24. ]
Max per column: [30 28 27 29 31]
Normalized data:
 [[0.4        0.53571429 0.51851852 0.34482759 0.41935484]
 [0.66666667 0.78571429 0.7037037  0.62068966 0.67741935]
 [1.         1.         1.         1.         1.        ]
 [0.83333333 0.85714286 0.96296296 0.79310345 0.70967742]]
Machines with avg > 20: [2 3]
Reshaped data:
 [[12 15 14 10 13 20 22 19 18 21]
 [30 28 27 29 31 25 24 26 23 22]]


In [3]:
import numpy as np

A = np.random.randint(1, 51, (3, 3))
B = np.random.randint(1, 51, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

mat_mult = A @ B
print("\nMatrix Multiplication:\n", mat_mult)

elem_mult = A * B
print("\nElement-wise Multiplication:\n", elem_mult)

greater_100 = mat_mult[mat_mult > 100]
print("\nElements > 100:\n", greater_100)

A[A < 10] = 0
B[B < 10] = 0

print("\nMatrix A after replace:\n", A)
print("Matrix B after replace:\n", B)

stacked = np.vstack((A, B))
print("\nStacked Matrix:\n", stacked)

Matrix A:
 [[27 17 25]
 [ 2 13 30]
 [15  5 18]]
Matrix B:
 [[ 4 24 29]
 [11 44 16]
 [41 33 15]]

Matrix Multiplication:
 [[1320 2221 1430]
 [1381 1610  716]
 [ 853 1174  785]]

Element-wise Multiplication:
 [[108 408 725]
 [ 22 572 480]
 [615 165 270]]

Elements > 100:
 [1320 2221 1430 1381 1610  716  853 1174  785]

Matrix A after replace:
 [[27 17 25]
 [ 0 13 30]
 [15  0 18]]
Matrix B after replace:
 [[ 0 24 29]
 [11 44 16]
 [41 33 15]]

Stacked Matrix:
 [[27 17 25]
 [ 0 13 30]
 [15  0 18]
 [ 0 24 29]
 [11 44 16]
 [41 33 15]]


In [4]:
import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, None, 2400, 5200, 15000]
}

df = pd.DataFrame(sales_data)

print("First 3 rows:\n", df.head(3))

print("\nMissing values:\n", df.isnull())

median_value = df["Amount"].median()
df["Amount"].fillna(median_value, inplace=True)

df["Amount"] = df["Amount"].astype(int)

print("\nCleaned Data:\n", df)

df.to_csv("cleaned_sales_data.csv", index=False)

print("\nFile saved as cleaned_sales_data.csv")

First 3 rows:
    OrderID Customer     City     Category   Amount
0      101      Ali  Karachi  Electronics  12000.0
1      102     Sara   Lahore     Clothing   3500.0
2      103    Ahmed  Karachi  Electronics      NaN

Missing values:
    OrderID  Customer   City  Category  Amount
0    False     False  False     False   False
1    False     False  False     False   False
2    False     False  False     False    True
3    False     False  False     False   False
4    False     False  False     False   False
5    False     False  False     False   False

Cleaned Data:
    OrderID Customer       City     Category  Amount
0      101      Ali    Karachi  Electronics   12000
1      102     Sara     Lahore     Clothing    3500
2      103    Ahmed    Karachi  Electronics    5200
3      104      Ali  Islamabad    Groceries    2400
4      105     Zain     Lahore     Clothing    5200
5      106     Sara    Karachi  Electronics   15000

File saved as cleaned_sales_data.csv


/tmp/ipykernel_9827/2328693884.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Amount"].fillna(median_value, inplace=True)


In [6]:
import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, 8000, 2400, 5200, 15000]
}

df = pd.DataFrame(sales_data)

df["HighValue"] = df["Amount"] > 10000
print("With HighValue column:\n", df)

karachi_orders = df[df["City"] == "Karachi"]
print("\nKarachi Orders:\n", karachi_orders)

electronics_high = df[(df["Category"] == "Electronics") & (df["Amount"] > 10000)]
print("\nElectronics with Amount > 10000:\n", electronics_high)

sorted_df = df.sort_values(by="Amount", ascending=False)
print("\nSorted Data:\n", sorted_df)

top_customers = df.groupby("Customer")["Amount"].sum().sort_values(ascending=False).head(2)
print("\nTop 2 Customers:\n", top_customers)

With HighValue column:
    OrderID Customer       City     Category  Amount  HighValue
0      101      Ali    Karachi  Electronics   12000       True
1      102     Sara     Lahore     Clothing    3500      False
2      103    Ahmed    Karachi  Electronics    8000      False
3      104      Ali  Islamabad    Groceries    2400      False
4      105     Zain     Lahore     Clothing    5200      False
5      106     Sara    Karachi  Electronics   15000       True

Karachi Orders:
    OrderID Customer     City     Category  Amount  HighValue
0      101      Ali  Karachi  Electronics   12000       True
2      103    Ahmed  Karachi  Electronics    8000      False
5      106     Sara  Karachi  Electronics   15000       True

Electronics with Amount > 10000:
    OrderID Customer     City     Category  Amount  HighValue
0      101      Ali  Karachi  Electronics   12000       True
5      106     Sara  Karachi  Electronics   15000       True

Sorted Data:
    OrderID Customer       City     Categ

In [7]:
import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, 8000, 2400, 5200, 15000]
}

df = pd.DataFrame(sales_data)

revenue_city = df.groupby("City")["Amount"].sum()
print("Revenue per City:\n", revenue_city)

avg_category = df.groupby("Category")["Amount"].mean()
print("\nAverage per Category:\n", avg_category)

unique_customers = df.groupby("City")["Customer"].nunique()
print("\nUnique Customers per City:\n", unique_customers)

pivot = pd.pivot_table(df, values="Amount", index="City", columns="Category", aggfunc="sum")
print("\nPivot Table:\n", pivot)

revenue_city_df = revenue_city.reset_index()
print("\nRevenue with reset index:\n", revenue_city_df)

Revenue per City:
 City
Islamabad     2400
Karachi      35000
Lahore        8700
Name: Amount, dtype: int64

Average per Category:
 Category
Clothing        4350.000000
Electronics    11666.666667
Groceries       2400.000000
Name: Amount, dtype: float64

Unique Customers per City:
 City
Islamabad    1
Karachi      3
Lahore       2
Name: Customer, dtype: int64

Pivot Table:
 Category   Clothing  Electronics  Groceries
City                                       
Islamabad       NaN          NaN     2400.0
Karachi         NaN      35000.0        NaN
Lahore       8700.0          NaN        NaN

Revenue with reset index:
         City  Amount
0  Islamabad    2400
1    Karachi   35000
2     Lahore    8700
